from enum import Enum


class FailureReason(str, Enum):
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    PASSWORD_PROTECTED = "PASSWORD_PROTECTED"
    PROCESSING_FAILED = "PROCESSING_FAILED"
